// UI Primitives - Single export point
export { default as Button } from './Button'
export { default as Card } from './Card'
export { default as Badge } from './Badge'
export { default as Input } from './Input'
export { default as Modal } from './Modal'
export { default as LoadingSpinner } from './LoadingSpinner'
export { default as Toast } from './Toast'
export { default as ToastContainer } from './ToastContainer'
export { default as ErrorMessage } from './ErrorMessage'
export { default as PriceDisplay } from './PriceDisplay'
export { default as ConfirmDialog } from './ConfirmDialog'
export { default as QuantityStepper } from './QuantityStepper'
export { default as Skeleton } from './Skeleton'
export { default as EmptyState } from './EmptyState'
export { default as Alert } from './Alert'
export { default as ErrorBoundary } from './ErrorBoundary'

// @deprecated Compatibility names while remaining legacy pages migrate.
export { default as InputField } from './Input'
export { default as FormField } from './form-field'
export { default as Label } from './label'
export { default as Dialog } from './Modal'
export { default as DialogContent } from './Modal'
export { default as DialogTitle } from './Modal'
export { default as Drawer } from './Modal'
export { default as AlertDialog } from './ConfirmDialog'
export { default as Spinner } from './LoadingSpinner'

